# -*- coding: utf-8 -*-
"""Kaggle Sales Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/109PCg_uHQzzlRpz9CJJ8PNdH1Vs6V_Hl
"""

!pip install opendatasets

import opendatasets as od

import pandas

import opendatasets as od
od.download('https://www.kaggle.com/datasets/syedanwarafridi/vehicle-sales-data')

import pandas as pd
import os

file_list = os.listdir('/content/vehicle-sales-data')

csv_file = [file for file in file_list if file.endswith('.csv')][0]

file_path = os.path.join('/content/vehicle-sales-data', csv_file)

data=pd.read_csv(file_path)

print(data.head())

data = data.drop_duplicates()

print(data.isnull().sum())

data = data.dropna()

data['model'] = data['model'].fillna('Unknown')
 data['year'] = data['year'].fillna(0)

data['Order year'] = pd.to_datetime(data['year'], errors='coerce')

data['make'] = data['make'].str.title()

data['condition'] = data['condition'].replace('[\$,]', '', regex=True).astype(int)

data.to_csv('sales_data_cleaned.csv', index=False)

print("Dataset cleaned and saved successfully!")